version: "3.7"
volumes:
  pgdata:
  redisdata:
services:
  db:
    image: postgres:13-alpine
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: -c shared_preload_libraries='pg_stat_statements' -c pg_stat_statements.track=all
    environment:
      - POSTGRES_DB=course_db
      - POSTGRES_USER=dj_user
      - POSTGRES_PASSWORD=password123
  redis:
    image: redis:latest
    ports:
      - "127.0.0.1:6370:6379"
    volumes:
      - redisdata:/data
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    environment:
      - DB_NAME=course_dj
      - DB_USER=dj_user
      - DB_PASSWORD=password123
      - FRONT_BASE_URL=http://localhost:80
      - BACKOFFICE_BASE_URL=http://localhost:80/backoffice
      - PORT_OFFSET=
    volumes:
      - ./api:/app:cached
      - ./config:/app/config:cached
    depends_on:
      - db
      - redis
    ports:
      - "127.0.0.1:8081:8080"
      - "127.0.0.1:5679:5678"
    stdin_open: true
    tty: true
  nginx:
    image: nginx:stable
    environment:
      - TZ=Asia/Tokyo
      - NGINX_ENVSUBST_OUTPUT_DIR=/tmp
      - PORT_OFFSET=
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:cached
      - ./nginx/templates/default.dev.conf.template:/etc/nginx/templates/default.conf.template:cached
    depends_on:
      - api
    ports:
      - "127.0.0.1:81:80"

  # https:
  #   image: nginx:stable
  #   environment:
  #     - TZ=Asia/Tokyo
  #   volumes:
  #     - ./nginx/ssl/nginx.conf:/etc/nginx/nginx.conf:cached
  #     - ./nginx/ssl:/etc/nginx/ssl:cached
  #   depends_on:
  #     - nginx
  #   ports:
  #     - "127.0.0.1:444:443"
